### ISSUE TITLE
Not working under python 2.7

### ISSUE THREAD

**Issue by Ja83La** [mad-tinkerer/python-rdm6300#3]
Took me some time to find out that I should use Python 3 ...

Here the error that results from trying to use python 2.7

pi@tiny:~/rdm6300 $ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdm6300
>>> r=rdm6300.Reader('/dev/ttyS0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rdm6300/reader.py", line 212, in __init__
    super().__init__(port, heartbeat_interval=None)
TypeError: super() takes at least 1 argument (0 given)

**Comment by mad-tinkerer** [comment]
Unfortunately, I have used up all of my RDM6300s at the moment, but this is something I would want to fix, so I had ordered a few more just to make sure I can test my changes with real hardware too.

I think I will get back to this in a month or so. OTOH I would really recommend using python 3 as you can create way better code in python 3, also python 2 is end of life (sunset) since 2020 Jan 1st

**Comment by passgpc** [comment]
Hello, first of all excuse my English because I use a translator to be able to communicate, secondly I want to thank you for this work that has made programming rfid cards much easier for me, very few people take the time to design and share your knowledge, that makes you a good person, thank you.
